### ISSUE TITLE
Tela cortada resolucao 2560 x 1080

### ISSUE THREAD

**Issue by chapzin** [birobirobiro/DevNews#2]
a tela fica cortada e sem scroll quando abro nessa resolução

**Comment by birobirobiro** [comment]
Fala @chapzin , obrigado por avisar.

Enviei um fix habilitando o scroll quando a resolução for maior que 2500px.

https://github.com/birobirobiro/DevNews/commit/d071ac491ef38413a077cfbd2fe122593499e32c

Pode verificar se funcionou agora?

Abraços! 🚀

**Comment by chapzin** [comment]
sim o scroll está agora normal, mais acredito pra experiencia do usuário mais interessante diminuir o tamanho da letra e enquadra tudo na tela 
![image](https://user-images.githubusercontent.com/930047/228110859-66a4e381-55b6-4322-9f31-ce3f076bc4c6.png)
